name: segmented_date_picker
description: "A fully customizable segmented date & time picker for Flutter with inline editing and popup calendar/time panels."
version: 0.0.4
homepage:
repository: https://github.com/Fasikawkn/segmented_date_picker
issue_tracker: https://github.com/Fasikawkn/segmented_date_picker/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
